
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/self_making
    username: root
    password: ksm2521101
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

coolsms:
  api:
    key: NCSNMPAEWSXOI1FQ
    secret: UZQRSNTQGRBBFOFALYF6L13NAVY1DOEU
    number: 01067991769
